### ISSUE TITLE
Add Functionality to the register button of the Top NavBar

### ISSUE THREAD

**Issue by ayaankhan98** [ayaankhan98/ccms#16]
Create a registration.html page
required fields are 
- first name (Mandatory)
- last name (Mandatory)
- username (Mandatory)
- email (Mandatory)
- password (Mandatory)
- confirm password (Mandatory)
- gender (Mandatory)
- mobile number (Mandatory)
- registration type (select box) (Mandatory)
  - Client ( for registration of client)
  - Lawyer ( for registration of lawyers)
  - Court computer operator (for registration of court computer operators)

Facilities like adding a case , updating case judgements from time to time is not accessed by everyone in other words we can say that everyone cannot add or modify or remove the cases this work should be under an authorised person (Court computer operators)

if the registration type choosed is of type lawyer then show more fields to take input of
- COP (Alpha Numeric code Issued By Bar Council Of India) (Mandatory)
- Enrollment Number (Alpha Numeric code Issued By Bar Council Of State) (Mandatory)
- Enrollment Date ( Date of enrollment in state bar council) (Mandatory)

if the registration type is Client
- don't ask for any further information

if registration type is Court Computer Operator then show more fields to take input of
- registration number (provided by government to that operator for the validation that the person is a computer operator)
- Court Location ( place where this operator is employed) (Mandatory)
- Court Type ( type of court in which this operator is employed) (Mandatory)
  - District Court 
  - High Court
  - Supreme Court

- Finally at the last a Captcha Field
- a Registration Button

** Page Must be responsive
** use Flask-WTF

**Comment by zhcet19** [comment]
Facilities like adding a new case, updating case status need to be added in registration page or in a separate page within it. if all these things would be on a single registration page it would be quite hecty.

**Comment by ayaankhan98** [comment]
no that is not the part of registration page, i just mentioned the role of computer operator to make the idea clear.

**Comment by ayaankhan98** [comment]
completed !
