### ISSUE TITLE
Jumbotron in templates/index.html (Homepage) is not responsive

### ISSUE THREAD

**Issue by ayaankhan98** [ayaankhan98/ccms#17]
Not Working Properly On Mobile Screen.

- a small part of jumbotron header is hidden behind the navbar

![Screenshot_20200120-150447](https://user-images.githubusercontent.com/43348292/72716568-70b1f500-3b98-11ea-8edf-9302daed5be8.png)

- list item text sticks to right

![Screenshot_20200120-150452](https://user-images.githubusercontent.com/43348292/72716569-727bb880-3b98-11ea-9e4c-6f1a1146395a.png)

**Comment by fredunit** [comment]
Would you like to add Css to working on it? I would like to try on it.

**Comment by ayaankhan98** [comment]
yes you can with CSS, but it would be nice if you will go with bootstrap.

**Comment by HashirGJ8842** [comment]
I am sorry, actually we had this covered already, forgot to close the issue
