### ISSUE TITLE
Add Functionality to Login Button of Top Navbar

### ISSUE THREAD

**Issue by ayaankhan98** [ayaankhan98/ccms#6]
create a login.html page, inherited from layout.html
it must have 
- a username input filed
- a password input field
- a remember me checkbox
- a login button
- a forgot password option

the page must be responsive

**Comment by Zaidtech** [comment]
I am working on this issue!!

**Comment by ayaankhan98** [comment]
okay go ahead.

**Comment by HashirGJ8842** [comment]
I would like to work on this issue!

**Comment by ayaankhan98** [comment]
sure, go ahead
