### ISSUE TITLE
fix the jumbotron of templates/index.html (HomePage)

### ISSUE THREAD

**Issue by ayaankhan98** [ayaankhan98/ccms#8]
- fix the jumbotron text-placement
and i am also thinkig to add image to make it more interactive

![Screenshot from 2020-01-18 17-41-48](https://user-images.githubusercontent.com/43348292/72663539-d75cd480-3a19-11ea-906d-c1659beec2a9.png)

**Comment by HashirGJ8842** [comment]
I would like to work on this issue.

**Comment by HashirGJ8842** [comment]
Can you please specify what exactly do you want. It's not clear, i have anyway made some changes to make the website look a little more attractive.

**Comment by ayaankhan98** [comment]
i am taking about the jumbotron text and button and the list item which are not properly in center, just fix these things,
and i am thinking to add a feature on the index page to make a search for a laywer or court case.

**Comment by HashirGJ8842** [comment]
Ok, i get you now, working on it.

**Comment by ayaankhan98** [comment]
okay go ahead
