### ISSUE TITLE
Add a Footer to templates/layout.html

### ISSUE THREAD

**Issue by ayaankhan98** [ayaankhan98/ccms#9]
- add a responsive bottom-fixed footer

**Comment by zhcet19** [comment]
working on it

**Comment by ayaankhan98** [comment]
okay go ahead

**Comment by zhcet19** [comment]
take a look at it

**Comment by ayaankhan98** [comment]
it is not responsive.

**Comment by zhcet19** [comment]
I tried using position attribute relative and absolute changes padding ,and it pretends to me that it was better than
